### ISSUE TITLE
when we use filters option and deploy jenkins with configuration as code, plugin is not able to read if secrets are more than 10

### ISSUE THREAD

**Issue by DeekshithSN** [jenkinsci/aws-secrets-manager-secret-source-plugin#113]
### Jenkins and plugins versions report

Jenkins Version - 2.346.3
aws secret manger Plugin Version - 1.1.0

### What Operating System are you using (both controller, and any agents involved in the problem)?

We are running jenkins as kubernetes pod using helm charts, below are chart details 

repo name - https://charts.jenkins.io 
chart name - jenkins
version - 3.5.14 

### Reproduction steps

          awsCredentialsProvider:
            cache: true
            listSecrets:
              filters:
                - key: name
                  values:
                    %{ for s in secrets ~}
                    - ${s}
                    %{ endfor ~}
Above is the aws secret manager plugin config used to deploy jenkins as code.
You can assume we are looping through secrets, in the above config.

when the secrets list less than 10 or 10, it works without any issue. But when we provide secrets more than 10 then jenkins is not able to read any of the secret.

When we check the logs it says 

Could not list credentials in Secrets Manager: message=[1 validation error detected: Value'[secret1, secrets2....' at 'filters.1.member.values' failed to satisfy constraint: Member must have length less than or equal to 10 (Service: AWSSecretsManager; Status Code: 400; Error Code: ValidationException; Request ID: 4674747477-abccoo-2433; Proxy: null)]

In documentation also I dont see a parameter to configure number of secrets. 
 

### Expected Results

We should have field by which we can configure number of secrets to read or all allowed secrets should be read.   

### Actual Results

We should have field by which we can configure number of secrets to read or all allowed secrets should be read.

**Comment by chriskilding** [comment]
Closing because this is only relevant to the Credentials Provider plugin (I know you've posted a separate issue for that).

The SecretSource plugin (this one) does not use a ListSecrets call, and therefore is unaffected by any filter options you might supply.
