### ISSUE TITLE
Be compatible with job-dsl

### ISSUE THREAD

**Issue by gui-don** [jenkinsci/aws-secrets-manager-secret-source-plugin#159]
### What feature do you want to see added?

Hello 👋 

Everything is fine with jcasc `configuration-as-code` plugin, but, while I can input encrypted secret values using the [job-dsl plugin](https://github.com/jenkinsci/job-dsl-plugin), secret manager source do not work…

Using `job-dsl` plugin, this configuration works:
```
usernamePassword {
  id('my_amazing_secret')
  description('my_amazing_secret')
  scope('GLOBAL')
  username('bugs')
  password('{AQAAABAAAAAgSOME_ENCRYPTED_THING}')
}
```
As the password is gonna be decrypted if the master key is correct.

When trying to use secret-manager, no luck:
```
usernamePassword {
  id('my_amazing_secret')
  description('my_amazing_secret')
  scope('GLOBAL')
  username('bugs')
  password('${bunny}')
}
```
As it seems to use the litteral `${bunny}` as a password value instead of fetching it.

Am I doing something wrong? If not, is it possible to add the feature?

I am trying to correctly scope secrets, so global credentials is not always the correct option.

**Comment by chriskilding** [comment]
The first thing to check here would be does this work with the default CasC secret source (I think that's the environment variables one)?

If it does then potentially it's something we can support. If not, then that would suggest CasC does not integrate with Job-DSL at an API level, which is not something we can fix within this plugin; the change would have to be made upstream.

**Comment by gui-don** [comment]
Seems like, only encrypted secrets works with job-dsl, I'm gonna create a ticket there.

Thanks
